### ISSUE TITLE
Roadmap and todos

### ISSUE THREAD

**Issue by cognitom** [riot/route#2]
See also the discussion on https://github.com/riot/riot/issues/1063.

### v2.0.0

- [x] move `router` to this separated submodule from `riot`
- [x] make it UMD comatible
- [x] drop IE8 support
- [x] 100% coverage
- [x] solve the naming conflict (riot-router or riot-route or...?)
- [x] publish to npm https://www.npmjs.com/package/riot-route
- [x] publish to bower http://bower.io/search/?q=riot-route

### v2.3.0
- [x] support HTML5 history API
- [x] base url option: `router.base('/foo')`
- [x] click event override: to avoid page reloading
- [x] url match: `router('/bar/*', function(id) { ... })` (allow only wild card)
- [x] 2-4x smaller than page.js
- [x] documentation
- [x] 100% coverage - ~~now 99%~~ Thanks! @GianlucaGuarini 

Any feedback is appreciated :smile:

**Comment by cognitom** [comment]
Basically I believe this module should be **minimal**. But in practical use, better to support these?

- URL matching: `/foo` then `function() {...}` and `/bar/:id` then `function(id) {...}` ...
- Queries: `?keyword=foo&offset=2`

Current API just support a single function as an argument:

```javascript
router(function(collection, id, action) {
  ...
})
```

I think we can safely extend API like this:

```javascript
router('/foo', function() { ... })
router('/bar/*', function(id) { ... })
router(function() { /* default action */ })
```

And we could use the last argument for the URL query:

```javascript
router(function(collection, id, action, query) {
  console.log('keyword:' + query.keyword)
})
```

**Comment by tipiirai** [comment]
I think the purpose of Riot router is precisely that: to be minimal. Should be safe to add to any project without adding extra bytes to the stack. If users need more elaborate routing they can pick from the wild array of other routers. 

I think we don't want to be just another router without any difference and for me the API has been enough so far.

Thoughts?

**Comment by cognitom** [comment]
Yeah, agreed. Thanks for your feedback. I don't want to make another router without any difference, too. Hmm.. but this feels too small, and others seems too big for me.
Anyway, in your point of view, do we need the support of history API?

**Comment by GianlucaGuarini** [comment]
@cognitom you have done a good job!
For the API I would like to support at least all the routing patterns supported by [pagejs](https://visionmedia.github.io/page.js/) avoiding the bloat of the useless features ( like automatic link listeners )

This could mean that probably we need to add the regex to the `riot-observable` and this is something I wanted always to do but I never had time to implement it

> Anyway, in your point of view, do we need the support of history API?

I would use __only__ the [history api](http://caniuse.com/#search=history), and we could add a note to our doc, that if you need to support old browsers you need to use a polyfill

> solve the naming conflict (riot-router or riot-route or...?)

You can open a new issue on the @gabrielmoreira's [repo](https://github.com/gabrielmoreira/riot-router/issues) asking him if he would like to free the npm domain like a did for [riot-observable](https://github.com/callumlocke/riot-observable/issues/1)
If he will not, we will find out

**Comment by cognitom** [comment]
@GianlucaGuarini page.js is in mind, too :smile_cat:
I think we can find the way, simple enough, consistent with original router and mixing the best part of page.js API.

I've created an issue on his repo. I'm not sure my English... I hope we get a good answer.

**Comment by GianlucaGuarini** [comment]
@cognitom well done!

**Comment by tipiirai** [comment]
How will riot-router differ from page.js?

**Comment by cognitom** [comment]
I'd like to add only these functionality to our router:

- pushState (history API)
- base url option: `router.base('/foo')`
- click event override: avoid page reloading
- url match: `router('/bar/*', function(id) { ... })` (allow only wild card)

I've found that the second and third are needed for pushState.
Compared to page.js, there's no context, no plugin, no complex match (url variable), no redirect and less code, I think. And of course it has consistency from the original `riot.router`. How about...?

**Comment by tipiirai** [comment]
Okay. Sounds good. I guess it's fairly easy to make 2-4x smaller implementation and stay lean. Currently page.js has [922 lines of code](https://github.com/visionmedia/page.js/blob/master/page.js).

**Comment by cognitom** [comment]
Yes, we can. Let's keep it small! :smile_cat:

**Comment by tipiirai** [comment]
Maybe worth taking a look at the existing [micro routers](http://microjs.com/#router) and make sure Riot router is something that doesn't already exist.

**Comment by cognitom** [comment]
@tipiirai good information. I'll check these well later. Replacable-parser feature seems one of our advantage.

**Comment by cognitom** [comment]
Almost done! Now it's 2,258 bytes if minified.
https://github.com/riot/route/blob/v2.3/lib/index.js
I'll add some tests and document.

**Comment by GianlucaGuarini** [comment]
@cognitom awesome job! 
@aMarCruz what's the status of the `riot-compiler` and `riot-tmpl`? May I help you on anything?
I think the next riot release will be really hot!

**Comment by cognitom** [comment]
The documentation updated.
https://github.com/riot/route/tree/v2.3/doc

New APIs here:

- [route(filter, callback)](https://github.com/riot/route/tree/v2.3/doc#routefilter-callback)
- [route.base(base)](https://github.com/riot/route/tree/v2.3/doc#routebasebase)
- [route.create()](https://github.com/riot/route/tree/v2.3/doc#routecreate)
- [route.query()](https://github.com/riot/route/tree/v2.3/doc#routequery)

`route.create()` is needed to handle the routing in deferent context. For example, we could use this router in multiple tags, but we can't control the order of routing over the tags. `route.query()` is a simple helper to get query from the current url. Useful, but it could be removed for the sake of minimalism.

#11 has not merged here, but the discussion with @kfreiman has been landed on `route.base()` function, thanks.

**Comment by a-moses** [comment]
any  example update  to the new riot-observable ?

**Comment by zcei** [comment]
Just wanted to mention, that switching over to HTML5 PushState worked like a charm for us, once `2.3(.1)` was released!

Only minor adjustments, and now the URLs are really slick. Thanks for the good work :+1:

**Comment by yannickoo** [comment]
:heart:

**Comment by cognitom** [comment]
Next roadmap is here #39
