### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cognitom** [riot/route#39]
Now it's time to think about the next :-)
- [x] server-side support #18 
- [x] replaceState #47
- [x] prepare to make it optional for Riot.js 2.4
- [ ] rewrite into ES6

Other candidates:
- `next()`? #25
- route deconstructor #36
- decode URI #29

Note: #36 would be nice, but I'd like to keep it small, too. #29 breaks specs.

**Comment by GianlucaGuarini** [comment]
For the `next` I see the router a good candidate for the es2015 generators

**Comment by GianlucaGuarini** [comment]
@cognitom can you make a new `riot-route` release please? I would like to roll out a new riot release this weekend

**Comment by cognitom** [comment]
@GianlucaGuarini Sure ;-)

**Comment by cognitom** [comment]
The next todo is rewriting the library into ES6.
https://www.npmjs.com/package/riot-route
- v2.3.13: server-side support (Dec 27)
- v2.3.14: replaceState (Jan 10)

**Comment by GianlucaGuarini** [comment]
A rewrite in es6 will bloat the library adding all the babel helper functions. I am skeptical about this

**Comment by GianlucaGuarini** [comment]
@cognitom could you update the doc as well please?

**Comment by cognitom** [comment]
@GianlucaGuarini ok added. https://github.com/riot/route/commit/28e6a0c7662273b418b33a2d7b8b90e6cdc6502f

Yeah, we got to compare the size of output by babel.

**Comment by GianlucaGuarini** [comment]
Closing this issue because it's related to an old router version. Please update to the latest `@riotjs/route` version if you can.
